# Generated by Django 4.2.7 on 2025-11-16 06:49

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_file_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word Document'), ('PPTX', 'PowerPoint'), ('XLSX', 'Excel'), ('TXT', 'Text File'), ('MD', 'Markdown'), ('IMAGE', 'Image'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.project'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
    ]
